// Use this quizData in your app.
module.exports = [
	{
			"question": "Which language runs in a web browser?",
			"a": "Java",
			"b": "C",
			"c": "Python",
			"d": "JavaScript",
			"correct": "d",
	},
	{
			"question": "What does CSS stand for?",
			"a": "Central Style Sheets",
			"b": "Cascading Style Sheets",
			"c": "Cascading Simple Sheets",
			"d": "Cars SUVs Sailboats",
			"correct": "b",
	},
	{
			"question": "What does HTML stand for?",
			"a": "Hypertext Markup Language",
			"b": "Hypertext Markdown Language",
			"c": "Hyperloop Machine Language",
			"d": "Helicopters Terminals Motorboats Lamborginis",
			"correct": "a",
	},
	{
			"question": "What year was JavaScript launched?",
			"a": "1996",
			"b": "1995",
			"c": "1994",
			"d": "none of the above",
			"correct": "b",
	},
	{
			"question": "Who created JavaScript?",
			"a": "Douglas Crockford",
			"b": "Sheryl Sandberg",
			"c": "Brendan Eich",
			"d": "Tim Berners-Lee",
			"correct": "c",
	},
	{
			"question": "Which of the following is a JavaScript framework?",
			"a": "Laravel",
			"b": "React",
			"c": "Django",
			"d": "Ruby on Rails",
			"correct": "b",
	},
	{
			"question": "What does 'DOM' stand for in JavaScript?",
			"a": "Document Object Model",
			"b": "Data Object Management",
			"c": "Digital Object Model",
			"d": "Desktop Object Mapping",
			"correct": "a",
	},
	{
			"question": "Which company developed JavaScript?",
			"a": "Microsoft",
			"b": "Netscape",
			"c": "Google",
			"d": "Mozilla",
			"correct": "b",
	},
	{
			"question": "What does '===' mean in JavaScript?",
			"a": "Assignment",
			"b": "Comparison",
			"c": "Strict equality comparison",
			"d": "Logical AND",
			"correct": "c",
	},
	{
			"question": "Which of the following is not a JavaScript data type?",
			"a": "String",
			"b": "Boolean",
			"c": "Integer",
			"d": "Undefined",
			"correct": "c",
	},
	{
			"question": "What is 'NaN' in JavaScript?",
			"a": "A number",
			"b": "An error",
			"c": "Not a Number",
			"d": "None of the above",
			"correct": "c",
	},
	{
			"question": "How do you declare a JavaScript variable?",
			"a": "let x;",
			"b": "var x;",
			"c": "x = 10;",
			"d": "All of the above",
			"correct": "d",
	},
	{
			"question": "Which method is used to convert JSON data to a JavaScript object?",
			"a": "JSON.parse()",
			"b": "JSON.stringify()",
			"c": "JSON.convert()",
			"d": "JSON.objectify()",
			"correct": "a",
	},
	{
			"question": "What keyword is used to define an asynchronous function in JavaScript?",
			"a": "async",
			"b": "await",
			"c": "promise",
			"d": "callback",
			"correct": "a",
	},
	{
			"question": "Which symbol is used for comments in JavaScript?",
			"a": "//",
			"b": "/* */",
			"c": "<!-- -->",
			"d": "Both a and b",
			"correct": "d",
	},
	{
			"question": "What is the result of `typeof null` in JavaScript?",
			"a": "null",
			"b": "object",
			"c": "undefined",
			"d": "function",
			"correct": "b",
	},
	{
			"question": "What is the correct way to write a JavaScript array?",
			"a": "var colors = (1:'red', 2:'green', 3:'blue')",
			"b": "var colors = ['red', 'green', 'blue']",
			"c": "var colors = 'red', 'green', 'blue'",
			"d": "var colors = {1:'red', 2:'green', 3:'blue'}",
			"correct": "b",
	},
	{
			"question": "How do you write 'Hello World' in an alert box?",
			"a": "msg('Hello World')",
			"b": "alert('Hello World')",
			"c": "alertBox('Hello World')",
			"d": "msgBox('Hello World')",
			"correct": "b",
	},
	{
			"question": "Which method adds one or more elements to the end of an array and returns the new length?",
			"a": "push()",
			"b": "pop()",
			"c": "shift()",
			"d": "unshift()",
			"correct": "a",
	},
	{
			"question": "Which of the following is used to iterate over an array in JavaScript?",
			"a": "for loop",
			"b": "forEach()",
			"c": "map()",
			"d": "All of the above",
			"correct": "d",
	},
	{
			"question": "Which operator is used to assign a value to a variable in JavaScript?",
			"a": "=",
			"b": "==",
			"c": "===",
			"d": "!=",
			"correct": "a",
	},
	{
			"question": "Which method is used to round a number to the nearest integer in JavaScript?",
			"a": "Math.ceil()",
			"b": "Math.round()",
			"c": "Math.floor()",
			"d": "Math.random()",
			"correct": "b",
	},
	{
			"question": "Which built-in function is used to convert a string to lowercase letters?",
			"a": "toLowerCase()",
			"b": "toLower()",
			"c": "lower()",
			"d": "changeCase(lower)",
			"correct": "a",
	},
	{
			"question": "What will the code `Boolean(0)` return?",
			"a": "true",
			"b": "false",
			"c": "0",
			"d": "undefined",
			"correct": "b",
	},
	{
			"question": "Which event occurs when the user clicks on an HTML element?",
			"a": "onmouseover",
			"b": "onchange",
			"c": "onmouseclick",
			"d": "onclick",
			"correct": "d",
	}
];
